### ISSUE TITLE
Why is not `__pycache__` being ignored?

### ISSUE THREAD

**Issue by joelibaceta** [nasa/PyTDA#14]
I'm wondering if exists any reason not to ignore the `__pycache__` folder; I could notice in this commit https://github.com/nasa/PyTDA/commit/32a0963ce85c83c6040985f751650812adb30b0c it could be an intentional action.

If there is no reason and it was just an omission, I propose the following PR https://github.com/nasa/PyTDA/pull/15

**Comment by tjlang** [comment]
This was an omission, thanks for cleaning it up. I will accept the PR.
