### ISSUE TITLE
Naming and metadata

### ISSUE THREAD

**Issue by nguy** [nasa/PyTDA#9]
Currently, it appears that regardless what operation you use for the volume (NTDA or straight SW conversion) a variable called _turbulence_ is added by default. I wonder if either this should be a different name for each OR whether more metadata could be attached to the new variable so that the user knows which operation was used? I would propose tagging a `calculation` attribute or such.

In addition, maybe a check should be performed to check if _turbulence_ (or whatever name chosen) is already in use in the file?

**Comment by tjlang** [comment]
I checked and there is a `turb_name` keyword you can set in the `pytda.calc_turb_vol` function. The default for that keyword is 'turbulence', but the user can change that there.

By default `pytda` has it set to automatically overwrite whatever field is there when adding to the `Radar` object. I kind of like that, but one thing I could do is add Py-ART's `replace_existing` flag as a keyword option and pass that thru. Or we could cease automatically adding a field and just have `calc_turb_vol` return a Py-ART field dictionary that the end user must then manually add (or maybe add the dictionary return as an option set by keyword). Thoughts?

**Comment by tjlang** [comment]
Closing since the user can customize the turb_name variable.
